In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
lungcancer = pd.read_csv("lung_cancer.csv")

In [3]:
lungcancer

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
0,M,69,1,2,2,1,1,2,1,2,2,2,2,2,2,YES
1,M,74,2,1,1,1,2,2,2,1,1,1,2,2,2,YES
2,F,59,1,1,1,2,1,2,1,2,1,2,2,1,2,NO
3,M,63,2,2,2,1,1,1,1,1,2,1,1,2,2,NO
4,F,63,1,2,1,1,1,1,1,2,1,2,2,1,1,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,F,56,1,1,1,2,2,2,1,1,2,2,2,2,1,YES
305,M,70,2,1,1,1,1,2,2,2,2,2,2,1,2,YES
306,M,58,2,1,1,1,1,1,2,2,2,2,1,1,2,YES
307,M,67,2,1,2,1,1,2,2,1,2,2,2,1,2,YES
308,M,62,1,1,1,2,1,2,2,2,2,1,1,2,1,YES

In [4]:
lungcancer.head(n=103) # Dataseti bÃ¶lme

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
0,M,69,1,2,2,1,1,2,1,2,2,2,2,2,2,YES
1,M,74,2,1,1,1,2,2,2,1,1,1,2,2,2,YES
2,F,59,1,1,1,2,1,2,1,2,1,2,2,1,2,NO
3,M,63,2,2,2,1,1,1,1,1,2,1,1,2,2,NO
4,F,63,1,2,1,1,1,1,1,2,1,2,2,1,1,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,M,64,1,2,2,2,1,2,2,1,1,2,1,2,1,YES
99,M,56,2,1,1,1,1,2,2,2,2,2,2,1,2,YES
100,M,58,2,1,1,1,1,1,2,2,2,2,1,1,1,YES
101,F,81,1,2,2,2,2,2,2,2,1,2,2,2,2,YES
102,M,64,2,1,1,1,1,2,2,2,2,2,2,1,2,YES

In [5]:
len(lungcancer.index) #Ä°ndex sayÄ±sÄ±

309

In [6]:
lungcancer["AGE"].mean() # Bulunan anket bireylerinin yaÅŸlarÄ±nÄ±n ortalamasÄ±

62.67313915857605

In [7]:
lungcancer["AGE"].max() # YapÄ±lan anketteki en yÃ¼ksek yaÅŸa sahip olan bireyin yaÅŸÄ±

87

In [8]:
lungcancer["AGE"].min() # YapÄ±lan anketteki en dÃ¼ÅŸÃ¼k yaÅŸa sahip olan bireyin yaÅŸÄ±

21

In [9]:
cancerpeopla=lungcancer[lungcancer["LUNG_CANCER"] == "YES"]  # KANSER OLANLARIN LÄ°STESÄ°

In [10]:
cancerpeopla

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
0,M,69,1,2,2,1,1,2,1,2,2,2,2,2,2,YES
1,M,74,2,1,1,1,2,2,2,1,1,1,2,2,2,YES
5,F,75,1,2,1,1,2,2,2,2,1,2,2,1,1,YES
6,M,52,2,1,1,1,1,2,1,2,2,2,2,1,2,YES
7,F,51,2,2,2,2,1,2,2,1,1,1,2,2,1,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,F,56,1,1,1,2,2,2,1,1,2,2,2,2,1,YES
305,M,70,2,1,1,1,1,2,2,2,2,2,2,1,2,YES
306,M,58,2,1,1,1,1,1,2,2,2,2,1,1,2,YES
307,M,67,2,1,2,1,1,2,2,1,2,2,2,1,2,YES
308,M,62,1,1,1,2,1,2,2,2,2,1,1,2,1,YES

In [11]:
cancerpeopla.to_csv("Cancer_People.csv")

In [12]:
nocancerpeopla=lungcancer[lungcancer["LUNG_CANCER"] == "NO"]  # KANSER OLMAYANLARIN LÄ°STESÄ°

In [13]:
nocancerpeopla

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
2,F,59,1,1,1,2,1,2,1,2,1,2,2,1,2,NO
3,M,63,2,2,2,1,1,1,1,1,2,1,1,2,2,NO
4,F,63,1,2,1,1,1,1,1,2,1,2,2,1,1,NO
8,F,68,2,1,2,1,1,2,1,1,1,1,1,1,1,NO
12,F,60,2,1,1,1,1,2,1,1,1,1,2,1,1,NO
14,M,69,2,1,1,1,1,1,2,2,2,2,1,1,2,NO
19,F,61,1,1,1,1,2,2,1,1,1,1,2,1,1,NO
22,F,21,2,1,1,1,2,2,2,1,1,1,2,1,1,NO
27,M,69,1,1,1,2,1,2,1,2,1,2,2,1,2,NO
29,M,55,1,2,1,1,1,2,1,2,2,2,2,1,1,NO
30,F,57,2,2,1,1,1,1,1,1,1,1,2,1,1,NO
32,M,56,2,2,2,1,1,1,1,1,1,1,2,2,1,NO
34,M,59,1,2,2,1,1,1,1,1,1,1,1,2,2,NO
37,F,56,1,1,1,1,2,1,1,2,1,1,2,2,1,NO
49,M,60,1,1,2,2,2,1,1,1,2,1,1,1,1,NO
61,F,60,1,2,2,1,1,1,1,1,1,2,1,1,1,NO
80,F,58,1,1,1,1,1,2,1,1,1,1,2,1,1,NO
129,F,63,1,1,1,1,2,2,1,1,1,1,2,1,1,NO
153,M,69,2,1,1,2,1,1,1,1,1,1,1,1,2,NO
154,F,64,2,2,1,2,2,1,1,1,1,1,1,1,1,NO
156,M,47,2,2,1,1,2,1,1,1,1,1,1,1,2,NO
157,F,57,2,2,1,2,1,1,1,1,1,1,1,1,2,NO
159,M,68,1,1,2,2,2,1,1,1,2,1,1,1,1,NO
171,F,57,1,2,2,1,1,1,1,1,1,2,1,1,1,NO
183,F,71,2,1,1,1,2,2,1,1,1,1,2,1,1,NO
207,M,63,2,1,1,2,1,1,1,1,1,2,2,1,1,NO
215,F,62,1,1,1,1,2,2,1,1,1,1,2,1,1,NO
221,M,61,1,1,2,2,2,1,1,1,2,1,1,1,1,NO
245,M,59,1,1,1,2,1,2,1,2,1,1,2,1,2,NO
249,M,68,2,1,2,1,1,2,1,1,1,1,1,1,1,NO
262,F,67,1,2,1,1,1,1,1,2,1,2,2,1,1,NO
266,F,55,2,1,2,1,1,2,1,1,1,1,1,1,1,NO
270,F,70,2,1,1,1,1,2,1,1,1,1,2,1,1,NO
272,M,64,2,1,1,1,1,1,2,2,2,2,1,1,2,NO
277,F,87,1,1,1,1,2,2,1,1,1,1,2,1,1,NO
280,F,59,2,1,1,1,2,2,2,1,1,1,2,1,1,NO
281,M,55,2,1,1,1,1,2,2,1,1,1,2,1,2,NO
282,M,46,1,2,2,1,1,1,1,1,1,1,1,2,2,NO
286,F,63,1,1,1,1,2,2,1,1,1,1,2,1,1,NO

In [14]:
nocancerpeopla.to_csv("nocancer_people.csv")

In [15]:
lungcancer["AGE"].nunique() # KAÃ‡ FARKLI YAÅž GRUBU OLDUÄžUNU GÃ–STERÄ°R

39

In [16]:
lungcancer["GENDER"].value_counts() # KAÃ‡ ERKEK VE KAÃ‡ KADIN OLDUÄžUNU GÃ–STERÄ°R

M    162
F    147
Name: GENDER, dtype: int64

In [17]:
lungcancer["AGE"].value_counts() # YAÅž GRUPLARINDA KAÃ‡ KÄ°ÅžÄ° OLDUÄžUNU GÃ–STERÄ°R

64    20
63    19
56    19
62    18
60    17
61    16
59    15
70    15
67    13
58    13
69    11
55    11
72    10
71    10
68     9
57     9
77     9
51     8
54     8
65     7
74     6
75     5
76     4
52     4
53     4
73     4
47     4
66     4
49     3
81     2
78     2
44     2
48     2
21     1
79     1
38     1
39     1
87     1
46     1
Name: AGE, dtype: int64

In [18]:
lungcancer.drop(["ANXIETY","SWALLOWING DIFFICULTY","CHRONIC DISEASE"], axis=1,inplace=True)  #RAPIDMINERDAN Ã–ÄžRENDÄ°ÄžÄ°M ETKÄ°SÄ° Ã‡OKTA FAZLA OLMAYAN KATEGORÄ°LERÄ° Ã‡IKARTIYORUZ

In [19]:
maxage=lungcancer[lungcancer["AGE"] == lungcancer["AGE"].max()]   # EN YÃœKSEK YAÅžA SAHÄ°P OLAN HASTAMIZIN Ã–ZELLÄ°KLERÄ° # 2 = EVET 1 = NO

In [20]:
maxage.to_csv("maximumageperson.csv")

In [21]:
minage=lungcancer[lungcancer["AGE"] == lungcancer["AGE"].min()]  # EN DÃœÅžÃœK YAÅžA SAHÄ°P OLAN HASTAMIZIN Ã–ZELLÄ°KLERÄ° # 2 = EVET 1 = NO

In [22]:
minage.to_csv("minumunageperson.csv")

In [23]:
df = pd.DataFrame(lungcancer["AGE"].sort_values(ascending=False)) # YaÅŸlara gÃ¶re sÄ±ralama

In [24]:
df

     AGE
277   87
83    81
101   81
204   79
69    78
..   ...
168   44
20    44
261   39
238   38
22    21

[309 rows x 1 columns]

In [25]:
ismsokingyes = lungcancer[lungcancer["SMOKING"]==2] # ANKETÄ°MÄ°ZDEKÄ° TOPLAM SÄ°GARA Ä°Ã‡ENLERÄ°N SAYISI

In [26]:
ismsokingyes

,GENDER,AGE,SMOKING,YELLOW_FINGERS,PEER_PRESSURE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,CHEST PAIN,LUNG_CANCER
1,M,74,2,1,1,2,2,1,1,1,2,2,YES
3,M,63,2,2,1,1,1,1,2,1,1,2,NO
6,M,52,2,1,1,2,1,2,2,2,2,2,YES
7,F,51,2,2,2,2,2,1,1,1,2,1,YES
8,F,68,2,1,1,2,1,1,1,1,1,1,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...
300,F,63,2,2,2,2,2,2,1,2,2,2,YES
302,F,65,2,2,2,2,1,2,1,2,2,1,YES
305,M,70,2,1,1,2,2,2,2,2,2,2,YES
306,M,58,2,1,1,1,2,2,2,2,1,2,YES
307,M,67,2,1,1,2,2,1,2,2,2,2,YES

In [27]:
ismsokingyes.to_csv("smokingpeople.csv")

In [28]:
issmokingcancer = ismsokingyes[ismsokingyes["LUNG_CANCER"]=="YES"]

In [29]:
issmokingcancer

,GENDER,AGE,SMOKING,YELLOW_FINGERS,PEER_PRESSURE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,CHEST PAIN,LUNG_CANCER
1,M,74,2,1,1,2,2,1,1,1,2,2,YES
6,M,52,2,1,1,2,1,2,2,2,2,2,YES
7,F,51,2,2,2,2,2,1,1,1,2,1,YES
9,M,53,2,2,2,1,2,1,2,1,1,2,YES
10,F,61,2,2,2,2,1,2,1,2,2,1,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...
300,F,63,2,2,2,2,2,2,1,2,2,2,YES
302,F,65,2,2,2,2,1,2,1,2,2,1,YES
305,M,70,2,1,1,2,2,2,2,2,2,2,YES
306,M,58,2,1,1,1,2,2,2,2,1,2,YES
307,M,67,2,1,1,2,2,1,2,2,2,2,YES

In [30]:
issmokingcancer.to_csv("smokingandcancer.csv")

In [31]:
whatisagecancerandsmoking = issmokingcancer[issmokingcancer["AGE"] == issmokingcancer["AGE"]] #KANSER OLAN HASTALARIN YAÅžLARI

In [32]:
whatisagecancerandsmoking  # KANSER OLUPTA SÄ°GARA Ä°Ã‡EN Ä°NSANLARIN SAYISI 155/309

,GENDER,AGE,SMOKING,YELLOW_FINGERS,PEER_PRESSURE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,CHEST PAIN,LUNG_CANCER
1,M,74,2,1,1,2,2,1,1,1,2,2,YES
6,M,52,2,1,1,2,1,2,2,2,2,2,YES
7,F,51,2,2,2,2,2,1,1,1,2,1,YES
9,M,53,2,2,2,1,2,1,2,1,1,2,YES
10,F,61,2,2,2,2,1,2,1,2,2,1,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...
300,F,63,2,2,2,2,2,2,1,2,2,2,YES
302,F,65,2,2,2,2,1,2,1,2,2,1,YES
305,M,70,2,1,1,2,2,2,2,2,2,2,YES
306,M,58,2,1,1,1,2,2,2,2,1,2,YES
307,M,67,2,1,1,2,2,1,2,2,2,2,YES

In [33]:
smokeandshortbreath = whatisagecancerandsmoking[whatisagecancerandsmoking["SHORTNESS OF BREATH"]==2] # SÄ°GARA Ä°Ã‡Ä°PTE NEFES DARLIÄžI Ã‡EKEN KANSER HASTALARI

In [34]:
smokeandshortbreath # 107/309

,GENDER,AGE,SMOKING,YELLOW_FINGERS,PEER_PRESSURE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,CHEST PAIN,LUNG_CANCER
1,M,74,2,1,1,2,2,1,1,1,2,2,YES
6,M,52,2,1,1,2,1,2,2,2,2,2,YES
7,F,51,2,2,2,2,2,1,1,1,2,1,YES
10,F,61,2,2,2,2,1,2,1,2,2,1,YES
13,M,58,2,1,1,2,2,2,2,2,2,2,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,M,65,2,2,2,2,2,1,1,1,2,1,YES
300,F,63,2,2,2,2,2,2,1,2,2,2,YES
302,F,65,2,2,2,2,1,2,1,2,2,1,YES
305,M,70,2,1,1,2,2,2,2,2,2,2,YES
307,M,67,2,1,1,2,2,1,2,2,2,2,YES

In [35]:
smokeandshortbreath.to_csv("smokingandshortbreath.csv")

In [36]:
chestpainandothers = smokeandshortbreath[smokeandshortbreath["CHEST PAIN"]==2] # SÄ°GARA NEFES DARLIÄžI ,KANSER AYRICA GÃ–ÄžÃœS AÄžRISI OLANLAR

In [37]:
chestpainandothers  # 63 / 309

,GENDER,AGE,SMOKING,YELLOW_FINGERS,PEER_PRESSURE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,CHEST PAIN,LUNG_CANCER
1,M,74,2,1,1,2,2,1,1,1,2,2,YES
6,M,52,2,1,1,2,1,2,2,2,2,2,YES
13,M,58,2,1,1,2,2,2,2,2,2,2,YES
16,M,75,2,1,1,1,2,2,2,2,2,2,YES
23,M,60,2,1,1,2,2,2,2,2,2,2,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,F,54,2,2,1,1,1,2,2,1,2,2,YES
298,M,62,2,1,1,2,1,2,2,2,2,2,YES
300,F,63,2,2,2,2,2,2,1,2,2,2,YES
305,M,70,2,1,1,2,2,2,2,2,2,2,YES
307,M,67,2,1,1,2,2,1,2,2,2,2,YES

In [38]:
chestpainandothers.to_csv("smoking-shortbreatandchestpaing.csv")

In [39]:
coughing = chestpainandothers[chestpainandothers["COUGHING"]==2] # SÄ°GARA,GÃ–ÄžÃœS AÄžRISI,Ã–KSÃœRÃœK,NEFES DARLIÄžI KANSER OLAN HASTALAR

In [40]:
len(coughing)

46

In [41]:
coughing # 46/309 # SÄ°GARA,GÃ–ÄžÃœS AÄžRISI,Ã–KSÃœRÃœK,NEFES DARLIÄžI KANSER OLAN HASTALAR

,GENDER,AGE,SMOKING,YELLOW_FINGERS,PEER_PRESSURE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,CHEST PAIN,LUNG_CANCER
6,M,52,2,1,1,2,1,2,2,2,2,2,YES
13,M,58,2,1,1,2,2,2,2,2,2,2,YES
16,M,75,2,1,1,1,2,2,2,2,2,2,YES
23,M,60,2,1,1,2,2,2,2,2,2,2,YES
40,M,68,2,1,1,2,2,1,2,2,2,2,YES
45,M,72,2,2,2,2,1,2,2,2,2,2,YES
46,M,62,2,2,1,1,2,1,1,2,2,2,YES
53,M,49,2,1,2,2,2,2,2,2,2,2,YES
59,M,69,2,2,2,2,2,1,2,2,2,2,YES
74,M,61,2,1,1,2,2,2,2,2,2,2,YES
77,M,56,2,1,1,2,2,2,2,2,2,2,YES
79,F,73,2,2,2,2,1,1,1,2,2,2,YES
94,M,48,2,1,1,2,2,1,2,2,2,2,YES
96,F,61,2,2,1,1,2,1,2,2,2,2,YES
99,M,56,2,1,1,2,2,2,2,2,2,2,YES
102,M,64,2,1,1,2,2,2,2,2,2,2,YES
104,F,72,2,2,2,2,1,1,1,2,2,2,YES
116,M,57,2,1,1,2,1,2,2,2,2,2,YES
126,M,51,2,1,1,2,1,2,2,2,2,2,YES
133,M,76,2,1,1,2,2,2,2,2,2,2,YES
141,M,62,2,1,1,2,1,2,2,2,2,2,YES
143,F,63,2,2,2,2,2,2,1,2,2,2,YES
148,M,70,2,1,1,2,2,2,2,2,2,2,YES
150,M,67,2,1,1,2,2,1,2,2,2,2,YES
163,M,68,2,1,2,2,2,2,2,2,2,2,YES
169,M,56,2,2,2,2,2,1,2,2,2,2,YES
184,M,72,2,1,1,2,2,2,2,2,2,2,YES
204,M,79,2,1,1,2,2,1,2,2,2,2,YES
206,F,71,2,2,1,1,2,1,2,2,2,2,YES
209,M,55,2,1,1,2,2,2,2,2,2,2,YES
212,M,58,2,1,1,2,2,2,2,2,2,2,YES
214,F,61,2,2,2,2,1,1,1,2,2,2,YES
225,M,59,2,1,2,2,2,2,2,2,2,2,YES
231,M,64,2,2,2,2,2,1,2,2,2,2,YES
241,M,59,2,1,1,2,2,2,2,2,2,2,YES
251,F,64,2,2,2,2,2,2,1,2,2,2,YES
256,M,60,2,1,1,2,2,2,2,2,2,2,YES
258,M,70,2,1,1,2,2,1,2,2,2,2,YES
264,M,70,2,1,1,2,1,2,2,2,2,2,YES
271,M,63,2,1,1,2,2,2,2,2,2,2,YES
274,M,56,2,1,1,1,2,2,2,2,2,2,YES
290,M,76,2,1,1,2,2,2,2,2,2,2,YES
298,M,62,2,1,1,2,1,2,2,2,2,2,YES
300,F,63,2,2,2,2,2,2,1,2,2,2,YES
305,M,70,2,1,1,2,2,2,2,2,2,2,YES
307,M,67,2,1,1,2,2,1,2,2,2,2,YES

In [42]:
coughing.to_csv("coughing.csv")

In [45]:
alcoholconsumeandothers = coughing[coughing["ALCOHOL CONSUMING"]==2] # HEM ALKOL HEM SÄ°GARA,Ã–KSÃœRÃœK,GÃ–ÄžÃœS AÄžRISI NEFES DARLIÄžI Ã‡EKENLERÄ°N LÄ°STESÄ°

In [46]:
alcoholconsumeandothers #39/309

,GENDER,AGE,SMOKING,YELLOW_FINGERS,PEER_PRESSURE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,CHEST PAIN,LUNG_CANCER
6,M,52,2,1,1,2,1,2,2,2,2,2,YES
13,M,58,2,1,1,2,2,2,2,2,2,2,YES
16,M,75,2,1,1,1,2,2,2,2,2,2,YES
23,M,60,2,1,1,2,2,2,2,2,2,2,YES
40,M,68,2,1,1,2,2,1,2,2,2,2,YES
45,M,72,2,2,2,2,1,2,2,2,2,2,YES
53,M,49,2,1,2,2,2,2,2,2,2,2,YES
59,M,69,2,2,2,2,2,1,2,2,2,2,YES
74,M,61,2,1,1,2,2,2,2,2,2,2,YES
77,M,56,2,1,1,2,2,2,2,2,2,2,YES
94,M,48,2,1,1,2,2,1,2,2,2,2,YES
96,F,61,2,2,1,1,2,1,2,2,2,2,YES
99,M,56,2,1,1,2,2,2,2,2,2,2,YES
102,M,64,2,1,1,2,2,2,2,2,2,2,YES
116,M,57,2,1,1,2,1,2,2,2,2,2,YES
126,M,51,2,1,1,2,1,2,2,2,2,2,YES
133,M,76,2,1,1,2,2,2,2,2,2,2,YES
141,M,62,2,1,1,2,1,2,2,2,2,2,YES
148,M,70,2,1,1,2,2,2,2,2,2,2,YES
150,M,67,2,1,1,2,2,1,2,2,2,2,YES
163,M,68,2,1,2,2,2,2,2,2,2,2,YES
169,M,56,2,2,2,2,2,1,2,2,2,2,YES
184,M,72,2,1,1,2,2,2,2,2,2,2,YES
204,M,79,2,1,1,2,2,1,2,2,2,2,YES
206,F,71,2,2,1,1,2,1,2,2,2,2,YES
209,M,55,2,1,1,2,2,2,2,2,2,2,YES
212,M,58,2,1,1,2,2,2,2,2,2,2,YES
225,M,59,2,1,2,2,2,2,2,2,2,2,YES
231,M,64,2,2,2,2,2,1,2,2,2,2,YES
241,M,59,2,1,1,2,2,2,2,2,2,2,YES
256,M,60,2,1,1,2,2,2,2,2,2,2,YES
258,M,70,2,1,1,2,2,1,2,2,2,2,YES
264,M,70,2,1,1,2,1,2,2,2,2,2,YES
271,M,63,2,1,1,2,2,2,2,2,2,2,YES
274,M,56,2,1,1,1,2,2,2,2,2,2,YES
290,M,76,2,1,1,2,2,2,2,2,2,2,YES
298,M,62,2,1,1,2,1,2,2,2,2,2,YES
305,M,70,2,1,1,2,2,2,2,2,2,2,YES
307,M,67,2,1,1,2,2,1,2,2,2,2,YES

In [47]:
alcoholconsumeandothers.to_csv("everythingandalcohol.csv")

In [48]:
wheezing = alcoholconsumeandothers[alcoholconsumeandothers["WHEEZING"]==2] # SÄ°GARA,HIRILTI,Ã–KSÃœRÃœK,GÃ–ÄžÃœS AÄžRISI,ALKOL ETKÄ°SÄ°,NEFES DARLIÄžI

In [49]:
wheezing #28 value /309

,GENDER,AGE,SMOKING,YELLOW_FINGERS,PEER_PRESSURE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,CHEST PAIN,LUNG_CANCER
6,M,52,2,1,1,2,1,2,2,2,2,2,YES
13,M,58,2,1,1,2,2,2,2,2,2,2,YES
16,M,75,2,1,1,1,2,2,2,2,2,2,YES
23,M,60,2,1,1,2,2,2,2,2,2,2,YES
45,M,72,2,2,2,2,1,2,2,2,2,2,YES
53,M,49,2,1,2,2,2,2,2,2,2,2,YES
74,M,61,2,1,1,2,2,2,2,2,2,2,YES
77,M,56,2,1,1,2,2,2,2,2,2,2,YES
99,M,56,2,1,1,2,2,2,2,2,2,2,YES
102,M,64,2,1,1,2,2,2,2,2,2,2,YES
116,M,57,2,1,1,2,1,2,2,2,2,2,YES
126,M,51,2,1,1,2,1,2,2,2,2,2,YES
133,M,76,2,1,1,2,2,2,2,2,2,2,YES
141,M,62,2,1,1,2,1,2,2,2,2,2,YES
148,M,70,2,1,1,2,2,2,2,2,2,2,YES
163,M,68,2,1,2,2,2,2,2,2,2,2,YES
184,M,72,2,1,1,2,2,2,2,2,2,2,YES
209,M,55,2,1,1,2,2,2,2,2,2,2,YES
212,M,58,2,1,1,2,2,2,2,2,2,2,YES
225,M,59,2,1,2,2,2,2,2,2,2,2,YES
241,M,59,2,1,1,2,2,2,2,2,2,2,YES
256,M,60,2,1,1,2,2,2,2,2,2,2,YES
264,M,70,2,1,1,2,1,2,2,2,2,2,YES
271,M,63,2,1,1,2,2,2,2,2,2,2,YES
274,M,56,2,1,1,1,2,2,2,2,2,2,YES
290,M,76,2,1,1,2,2,2,2,2,2,2,YES
298,M,62,2,1,1,2,1,2,2,2,2,2,YES
305,M,70,2,1,1,2,2,2,2,2,2,2,YES

In [50]:
wheezing.to_csv("wheezing.csv")

In [51]:
yellow_fingers = wheezing[wheezing["YELLOW_FINGERS"]==2]

In [52]:
yellow_fingers # POPULASYON SÄ°GARA,((SARI PARMAK!)),TÃœKENMÄ°ÅžLÄ°K,HIRILTI,ALKOL ETKÄ°SÄ°,Ã–KSÃœRÃœK,NEFES DARLIÄžI VE GÃ–ÄžÃœS AÄžRISI OLAN BÄ°R HASTANIN KANSER OLUP OLMADIÄžI HAKKINDA BÄ°LGÄ°

,GENDER,AGE,SMOKING,YELLOW_FINGERS,PEER_PRESSURE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,CHEST PAIN,LUNG_CANCER
45,M,72,2,2,2,2,1,2,2,2,2,2,YES

In [53]:
yellow_fingers.to_csv("yellowfingersandothers.csv")

In [54]:
peerpressure = wheezing[wheezing["PEER_PRESSURE"]==2] # POPULASYON, (((AKRAN BASKISI!)),TÃœKENMÄ°ÅžLÄ°K,HIRILTI,ALKOL ETKÄ°SÄ°,Ã–KSÃœRÃœK,NEFES DARLIÄžI VE GÃ–ÄžÃœS AÄžRISI OLAN BÄ°R HASTANIN KANSER OLUP OLMADIÄžI HAKKINDA BÄ°LGÄ°

In [55]:
peerpressure # 4/309 HEPSÄ° ERKEK

,GENDER,AGE,SMOKING,YELLOW_FINGERS,PEER_PRESSURE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,CHEST PAIN,LUNG_CANCER
45,M,72,2,2,2,2,1,2,2,2,2,2,YES
53,M,49,2,1,2,2,2,2,2,2,2,2,YES
163,M,68,2,1,2,2,2,2,2,2,2,2,YES
225,M,59,2,1,2,2,2,2,2,2,2,2,YES

In [56]:
peerpressure.to_csv("peerpressure.csv")

In [57]:
iscancerF=lungcancer[lungcancer["GENDER"]=="F"] # ANKETTEKÄ° KADINLAR

In [58]:
iscancerF

,GENDER,AGE,SMOKING,YELLOW_FINGERS,PEER_PRESSURE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,CHEST PAIN,LUNG_CANCER
2,F,59,1,1,2,2,1,2,1,2,2,2,NO
4,F,63,1,2,1,1,1,2,1,2,2,1,NO
5,F,75,1,2,1,2,2,2,1,2,2,1,YES
7,F,51,2,2,2,2,2,1,1,1,2,1,YES
8,F,68,2,1,1,2,1,1,1,1,1,1,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,F,54,2,2,1,1,1,2,2,1,2,2,YES
297,F,47,2,2,2,2,2,2,1,2,2,1,YES
300,F,63,2,2,2,2,2,2,1,2,2,2,YES
302,F,65,2,2,2,2,1,2,1,2,2,1,YES
304,F,56,1,1,2,2,1,1,2,2,2,1,YES

In [59]:
iscancerF.to_csv("femalecancer.csv")

In [64]:
isfemalecancer = iscancerF[iscancerF["LUNG_CANCER"]=="YES"]

In [65]:
isfemalecancer #KANSER OLAN KADINLARIN SAYISI 125

,GENDER,AGE,SMOKING,YELLOW_FINGERS,PEER_PRESSURE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,CHEST PAIN,LUNG_CANCER
5,F,75,1,2,1,2,2,2,1,2,2,1,YES
7,F,51,2,2,2,2,2,1,1,1,2,1,YES
10,F,61,2,2,2,2,1,2,1,2,2,1,YES
15,F,48,1,2,2,2,2,2,1,2,2,1,YES
18,F,68,2,2,2,2,1,1,1,2,2,1,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,F,54,2,2,1,1,1,2,2,1,2,2,YES
297,F,47,2,2,2,2,2,2,1,2,2,1,YES
300,F,63,2,2,2,2,2,2,1,2,2,2,YES
302,F,65,2,2,2,2,1,2,1,2,2,1,YES
304,F,56,1,1,2,2,1,1,2,2,2,1,YES

In [66]:
iscancerm= lungcancer[lungcancer["GENDER"]=="M"] # ANKETTEKÄ° ERKEKLER

In [67]:
iscancerm

,GENDER,AGE,SMOKING,YELLOW_FINGERS,PEER_PRESSURE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,CHEST PAIN,LUNG_CANCER
0,M,69,1,2,1,2,1,2,2,2,2,2,YES
1,M,74,2,1,1,2,2,1,1,1,2,2,YES
3,M,63,2,2,1,1,1,1,2,1,1,2,NO
6,M,52,2,1,1,2,1,2,2,2,2,2,YES
9,M,53,2,2,2,1,2,1,2,1,1,2,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...
303,M,51,1,2,1,2,2,2,2,2,2,2,YES
305,M,70,2,1,1,2,2,2,2,2,2,2,YES
306,M,58,2,1,1,1,2,2,2,2,1,2,YES
307,M,67,2,1,1,2,2,1,2,2,2,2,YES
308,M,62,1,1,2,2,2,2,2,1,1,1,YES

In [68]:
iscancermale = iscancerm[iscancerm["LUNG_CANCER"]=="YES"]

In [69]:
iscancermale # KANSER OLAN ERKEKLERÄ°N SAYISI 145

,GENDER,AGE,SMOKING,YELLOW_FINGERS,PEER_PRESSURE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,CHEST PAIN,LUNG_CANCER
0,M,69,1,2,1,2,1,2,2,2,2,2,YES
1,M,74,2,1,1,2,2,1,1,1,2,2,YES
6,M,52,2,1,1,2,1,2,2,2,2,2,YES
9,M,53,2,2,2,1,2,1,2,1,1,2,YES
11,M,72,1,1,1,2,2,2,2,2,2,2,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...
303,M,51,1,2,1,2,2,2,2,2,2,2,YES
305,M,70,2,1,1,2,2,2,2,2,2,2,YES
306,M,58,2,1,1,1,2,2,2,2,1,2,YES
307,M,67,2,1,1,2,2,1,2,2,2,2,YES
308,M,62,1,1,2,2,2,2,2,1,1,1,YES

In [70]:
iscancermale.to_csv("cancermale.csv")